declare module HyperscriptHelpers {
    interface HyperscriptHelpers {
        a(...params): Object;
        abbr(...params): Object;
        address(...params): Object;
        area(...params): Object;
        article(...params): Object;
        aside(...params): Object;
        audio(...params): Object;
        b(...params): Object;
        base(...params): Object;
        bdi(...params): Object;
        bdo(...params): Object;
        blockquote(...params): Object;
        body(...params): Object;
        br(...params): Object;
        button(...params): Object;
        canvas(...params): Object;
        caption(...params): Object;
        cite(...params): Object;
        code(...params): Object;
        col(...params): Object;
        colgroup(...params): Object;
        dd(...params): Object;
        del(...params): Object;
        dfn(...params): Object;
        dir(...params): Object;
        div(...params): Object;
        dl(...params): Object;
        dt(...params): Object;
        em(...params): Object;
        embed(...params): Object;
        fieldset(...params): Object;
        figcaption(...params): Object;
        figure(...params): Object;
        footer(...params): Object;
        form(...params): Object;
        h1(...params): Object;
        h2(...params): Object;
        h3(...params): Object;
        h4(...params): Object;
        h5(...params): Object;
        h6(...params): Object;
        head(...params): Object;
        header(...params): Object;
        hgroup(...params): Object;
        hr(...params): Object;
        html(...params): Object;
        i(...params): Object;
        iframe(...params): Object;
        img(...params): Object;
        input(...params): Object;
        ins(...params): Object;
        kbd(...params): Object;
        keygen(...params): Object;
        label(...params): Object;
        legend(...params): Object;
        li(...params): Object;
        link(...params): Object;
        map(...params): Object;
        mark(...params): Object;
        menu(...params): Object;
        meta(...params): Object;
        nav(...params): Object;
        noscript(...params): Object;
        object(...params): Object;
        ol(...params): Object;
        optgroup(...params): Object;
        option(...params): Object;
        p(...params): Object;
        param(...params): Object;
        pre(...params): Object;
        q(...params): Object;
        rp(...params): Object;
        rt(...params): Object;
        ruby(...params): Object;
        s(...params): Object;
        samp(...params): Object;
        script(...params): Object;
        section(...params): Object;
        select(...params): Object;
        small(...params): Object;
        source(...params): Object;
        span(...params): Object;
        strong(...params): Object;
        style(...params): Object;
        sub(...params): Object;
        sup(...params): Object;
        table(...params): Object;
        tbody(...params): Object;
        td(...params): Object;
        textarea(...params): Object;
        tfoot(...params): Object;
        th(...params): Object;
        thead(...params): Object;
        title(...params): Object;
        tr(...params): Object;
        u(...params): Object;
        ul(...params): Object;
        video(...params): Object;
    }
}

declare const HyperscriptHelpers: (h) => HyperscriptHelpers.HyperscriptHelpers;

declare module "hyperscript-helpers" {
    export = HyperscriptHelpers;
}
